### PR TITLE
Remove some unused faces of crimson and warped doors

### PR DESCRIPTION
**Pull request by Rayzeq**

### CODE REVIEW

**Comment by Juknum** [comment]
Does this PR remove textures between the top & bottom of the block? If so it's intended, for map makes that may use only half of the door.

**Comment by Juknum** [comment]
If you can link screenshots of what changed :p

**Comment by Rayzeq** [comment]
Yes, it removes the textures between the top and bottom of the block, I didn't know that had any use. But these are the only doors that have these textures, and the textures are visible only when the doors are open (and IIRC the default model doesn't have them). And if you really want to keep them, I think there's still some tweaking to do because there's a lot of z-fighting.
image
(this is the unmodified model, the door is open, otherwise it's transparent)

**Comment by Juknum** [comment]
Oh that's pretty weird, I know that the shader used for the bookshelf can do such z-fighting, this needs to be investigated

**Pull request merged**
